In [6]:
import pandas as pd
import numpy as np
from yahoo_fin import stock_info as si
from matplotlib import pyplot as plt
from plotly import express as px

company = si.get_data('sbux')
company = company.loc['2021-01-04':'2023-11-14']

In [7]:
company

,open,high,low,close,adjclose,volume,ticker
2021-01-04,107.660004,107.750000,102.139999,103.099998,97.033081,8041500,SBUX
2021-01-05,102.919998,104.260002,102.800003,103.440002,97.353081,5721900,SBUX
2021-01-06,102.989998,105.209999,102.910004,104.190002,98.058937,5017200,SBUX
2021-01-07,104.489998,104.639999,102.949997,103.349998,97.268372,5057000,SBUX
2021-01-08,103.860001,105.760002,103.419998,105.669998,99.451843,5869700,SBUX
...,...,...,...,...,...,...,...
2023-11-08,103.739998,104.820000,103.650002,104.300003,103.730003,7453000,SBUX
2023-11-09,104.300003,104.459999,102.029999,102.230003,102.230003,7607000,SBUX
2023-11-10,102.599998,104.349998,101.980003,104.330002,104.330002,7338500,SBUX
2023-11-13,103.919998,104.230003,102.959999,103.510002,103.510002,7120800,SBUX
2023-11-14,104.480003,105.820000,104.239998,105.599998,105.599998,8323000,SBUX

In [8]:
company["date"] = company.index

In [9]:
company = company.reset_index()

In [11]:
company["yesterday"] = company["close"].shift(1) 
company = company.fillna(company["close"][0])
company["%change"] = (company["close"]- company["yesterday"]) / company["yesterday"]
company

,index,open,high,low,close,adjclose,volume,ticker,date,yesterday,%change
0,2021-01-04,107.660004,107.750000,102.139999,103.099998,97.033081,8041500,SBUX,2021-01-04,103.099998,0.000000
1,2021-01-05,102.919998,104.260002,102.800003,103.440002,97.353081,5721900,SBUX,2021-01-05,103.099998,0.003298
2,2021-01-06,102.989998,105.209999,102.910004,104.190002,98.058937,5017200,SBUX,2021-01-06,103.440002,0.007251
3,2021-01-07,104.489998,104.639999,102.949997,103.349998,97.268372,5057000,SBUX,2021-01-07,104.190002,-0.008062
4,2021-01-08,103.860001,105.760002,103.419998,105.669998,99.451843,5869700,SBUX,2021-01-08,103.349998,0.022448
...,...,...,...,...,...,...,...,...,...,...,...
717,2023-11-08,103.739998,104.820000,103.650002,104.300003,103.730003,7453000,SBUX,2023-11-08,103.680000,0.005980
718,2023-11-09,104.300003,104.459999,102.029999,102.230003,102.230003,7607000,SBUX,2023-11-09,104.300003,-0.019847
719,2023-11-10,102.599998,104.349998,101.980003,104.330002,104.330002,7338500,SBUX,2023-11-10,102.230003,0.020542
720,2023-11-13,103.919998,104.230003,102.959999,103.510002,103.510002,7120800,SBUX,2023-11-13,104.330002,-0.007860
721,2023-11-14,104.480003,105.820000,104.239998,105.599998,105.599998,8323000,SBUX,2023-11-14,103.510002,0.020191